name: Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Format check
        run: npx dprint check
      - name: Type check
        run: npm run tsc

  test-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run ci readme

  test-node18:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "18.19.x"
          - "18.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run ci node18

  test-node20:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run ci node20

  test-node21:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "21.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run ci node21

  test-node22:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "22.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run ci node22
