name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci readme

  test-node18:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "18.19.x"
          - "18.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci node18

  test-node20:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci node20

  test-node21:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "21.x"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci node21

  publish:
    needs:
      - test-readme
      - test-node18
      - test-node20
      - test-node21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"
      - name: Pin package version
        run: |
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}
          npm version --allow-same-version ${GITHUB_REF#refs/*/}
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
